version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-crediya
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crediya
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/postgresql/scripts/data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - crediya-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crediya"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure  

  auth-service:
    build:
      context: ./
      dockerfile: deployment/Dockerfile
    container_name: auth-service
    image: auth-service:local
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: CrediYa
      SPRING_PROFILES_ACTIVE: docker

      JWT_SECRET: "H8PVV7h2qr3AnAhpJ5vRCEHDbGP1Vm5R"
      JWT_ISSUER: "crediya-auth"

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crediya
      DB_SCHEMA: auth
      DB_USER: dev_user
      DB_PASSWORD: dev123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crediya-net
    restart: on-failure

  nginx:
    build:
      context: ./deployment/nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - auth-service
    networks:
      - crediya-net


volumes:
  pgdata:

networks:
  crediya-net:
    driver: bridge
