server {
    listen 80;
    server_name crediya;

    location /auth/ {
        proxy_pass http://auth-service:8080/;
    }

    location /loans/ {
        proxy_pass http://loan-service:8082/;
    }
}